name: Manual Helm Download

# This section enables the manual "Run workflow" button in the GitHub UI
on:
  workflow_dispatch:
    # inputs:
    #   helm_version:
    #     description: 'Helm Version (e.g., v3.14.4 or latest)'
    #     required: true
    #     default: 'latest'

jobs:
  download_helm:
    runs-on: ubuntu-latest
    steps:
      - name: ⬇️ Checkout code
        uses: actions/checkout@v4

      # - name: ⚙️ Setup Helm with Input Version
      #   uses: azure/setup-helm@v4
      #   # with:
      #   #   # Use the version provided in the manual trigger form, 
      #   #   # otherwise fall back to the default 'latest'
      #   #   version: ${{ github.event.inputs.helm_version }}

      # - name: ✅ Verify Helm Installation
      #   run: |
      #     echo "Successfully installed Helm version:"
      #     helm version --short


      - name: ⬇️ Manual Helm Installation (using Installer Script)
        run: |
          # This downloads and runs the official get-helm-3 script, which finds the latest version
          curl -fsSL https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
          helm version --client